name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Build Artifact
        run: npm build
      - name: Deploy to Production
        uses: some-deployment-action@v1
        with:
          environment: production
          token: ${{ secrets.DEPLOY_TOKEN }}
    ```
